---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: binary_install
    run_list:
      - recipe[packer::default]
    attributes:

  - name: source_install
    run_list:
      - recipe[packer::default]
    attributes:
      packer:
        install_method: 'source'
